* emacs
** TASKS
** main

modify DIRED
- keybindings with EVIL

modify DocView
- resolution
- EVIL bindings?

magit
autosave
undo / redo maturity
automatic tabbing


learn what the bar is
recon DOOM emacs

completed:
    modify the terminal emulator
    get solarized theme
    no backup files
    github!! what's going on?



** emacs mech
- ORG MODE
- org mode init for filetypes
- DIRED
- all of info navigation (package docs)


- all of info navigation


** filetypes
            - compile LaTeX quickly & unprompted
- LaTeX spell check
- LaTeX no indent

- python autocomplete
** vim emulation
- find in line
- find backwards
- substitute
- replace in parenthesis
- undo undo (redo)
- vim dot command
- mu4e?
- macros


** play
there is no pain you are receding
a distant ship smoke on the horizon
you are only coming through in waves
your lips move, but I can't hear what you're saying
when I was a child, I caught a fleeting glimpse
out of the corner of my eye
I turned to look, but it was gone,
I cannot put my finger on it now

hello darkness my old friend
I've come to talk with you again
because a vision softly creeping
left its seeds while I was sleeping
and the vision that was planted in my brain
still remains
within the sound of silence

in restless dreams I walked alone
through narrow streets of cobblestone
'neath the halo of a streetlamp
I turned my collar to the cold and damp
when my eyes were stabbed by the flash of a neon light
that split the night
and touched the sound of silence

and in the light I saw
ten thousand people maybe more
people talking without speaking
people hearing without listening
people writing songs that voices never share
and no one dared
disturb the sound of silence

fools said I you do not know
silence like the cancer grows
hear my words that I might teach you
take my arms that I might reach you
but my words like silent raindrops fell
and echoed
in the wells of silence

and the people bowed and prayed
to the neon god they made
and the sign flashed its warning
in the words that it was forming
and the sign said, "the words of the prophet are written on the subway walls
and tenement halls"
and whispered in the sound of silence


| data1 | data2 | data4 |
|     1 |     2 |     4 |
|     2 |     3 |     5 |
|     3 |     4 |     4 |
|     4 |   5.3 |    32 |
|     5 |     6 |    34 |
|     7 |     8 |     3 |
|     8 |     9 |    23 |
|     9 |    10 |    14 |
|    10 |    10 |    45 |
|    11 |    11 |     1 |
|    12 |    15 |    34 |
|    13 |    23 |    34 |
|    14 |    14 |    23 |
|    15 |   324 |    12 |
|    16 |    43 |    55 |
|    17 |    08 |    34 |
|    23 |    34 |    90 |

** fold
#+begin_src python
  print("hello")
  for i in range(1,10): print(i)
#+end_src

hello darkness my old friend
i've come to talk with you again
because a vision softly creeping
left its seeds while I was sleeping
and the vision
that was planted in my brain
stil remains

within the sound of silence

in restless dreams I walk alone
through narrow streets of cobblestone
underneath the halo of a streetlamp
I turned my collar to the cold and damp
when my eyes were stabbed by the flash of a neon light
that split the night
and touched the sound of silence

fools said I you do not know
silence like the cancer grows
hear my words that I might teach you
take my arms that I might reach you
but my words like silent raindrops fell
and echoed in the wells of silence

and the people bowed and prayed
to the neon god they made
and the sign flashed out its warning
in the words that it was forming
and the sign said the words of the prophet are written on the subway walls
and tenement halls
within the sound of silence





** VIM vs Emacs

  | vim                         | Emacs                     |
  |-----------------------------+---------------------------|
  | fast startup                | better config language    |
  | native keybindings          | org mode + tables         |
  | simplistic layout           | better package management |
  | netrw                       | LSP mode                  |
  | better paired with terminal | ivy mode                  |
  | vanilla is better           | better gui handling       |
* stumpwm
  
white borders around certain applications and closed windows

mute button
volume up and down button
    graphic display of it
mute microphone button
brightness up and down button
    graphic display of it

wallpaper

wifi

bluetooth

nvidia hybrid mode

sound (microphone)

mouse speed

open config file

printing

floating terminal & matplotlib?

theming easier
font on modeline


* i3

volume cap

brightness up and down

graphic display of volume and brightness

nvidia hybrid mode

wifi & bluetooth

mouse speed

open config file

printing

floating terminal & matplotlib?


wallpaper
