* why 
to whomever it may concern,

quick learner at Slooh
passionate about computation

lifelong interest in space
I love the idea of Unst

would you be willing to act as a reference for me
I'll certainly let you know



* draft:

Thank you so much for considering me for a position at Shetland Space. The more I learn about your company, the more I can't help but dream that I could be a part of it.

The possible opportunity of working within The Shetland Space Center is thrilling. I am currently in my final year of my BSc Physics degree at the University of St Andrews, and I believe that with my combined knowledge of physics and computation, I can make myself valuable as part of your team.

For as long as I can remember, I have believed that my future would be within the space industry. Ever since it became up to me, through secondary school and university, I have made an effort to take as many physics, math, and astrophysics classes as I could.

That is also why I was thrilled to be a part of Slooh.com, a website that provides users with remote access to large telescopes in the Canary Islands and Chile. While I was there, the website also extended its educational capacity which included guided tours of the basic, observable aspects of the night sky.

I can offer an easygoing personality, a commitment to figuring anything out, zero need for creature comfort, huge interest in adventure, and perhaps most importantly, and actual desire to live and work in a remote and beautiful place.

There is no job or task that I will see that is beneath me.

I've attached my resume, which further details my skills and education. Please do not hesitate to reach out if you have any questions, and I look forward to the opportunity to speak you further. Thank you for your time and consideration.

Sincerely,
Jack


Looking at the images posted on the S.S.C. website, my jaw drops at what looks like a fantasy-painting come to life.

I loved its mission, which was to attempt to close the gap between the practice of observing the night sky and everyone that is not an astronomer working at a telescope facility.

As someone who went to a boarding school, then to University across the Atlantic, I can safely say that I don't shy from 
adventure. Looking at the images posted on the S.S.C. website, my jaw drops at what looks like a fantasy-painting come to life.
* mummy draft
Thank you so much for considering me for a position at Shetland Space. The more I learn about your company, the more I can't help but dream that I could be a part of its growth. I am currently in my final year of my BSc Physics degree at the University of St. Andrews. I believe that with my combined knowledge of physics, computer systems, and programming, I can make myself a valuable addition to your team.

At the risk of sounding mushy, for as long as I can remember, I have believed that my future would be within the space industry. Ever since it became up to me, through secondary school and university, I have made an effort to take as many physics, math, and astrophysics classes as I could. That is why I was thrilled to be a part of Slooh.com, a website that provides users with remote access to telescopes in the Canary Islands and Chile. While I was there, the website also extended its educational capacity, which included guided tours of the basic, observable aspects of the night sky. I was able to put myself in the shoes of a student as I attempted to explain essential astronomy as elegantly as possible. Additionally, I was able to teach myself the technologies used there within a couple of days.

Of course, the idea of participating in the development of a satelite launch site is exactly 
how I have always hoped I could apply myself and contribute to the advancement of space operations in the U.K. I will accept any job or task that is offered if it means I can be part of Shetland Space. I can offer an easygoing personality, a commitment to figuring anything out, zero need for creature comfort, strong interest in adventure, and perhaps most importantly, an earnest desire to live and work in a remote and beautiful place.

I've attached my resume, which further details my skills and education. Please do not hesitate to reach out if you have any questions, and I look forward to the opportunity to speak to you further. I also have references available upon request. Thank you for your time and consideration.


Sincerely,
Jack
